# Generated by Django 2.2 on 2021-03-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_marks', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_marks',
        ),
    ]
