# Generated by Django 2.2 on 2021-03-10 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20210310_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_marsk', to='demo.Student'),
        ),
    ]
